name: Build & Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Create ECR repository if it doesn't exist
      run: |
        if ! aws ecr describe-repositories --repository-names sairam-strapi-ecr --region ap-south-1 > /dev/null 2>&1; then
          aws ecr create-repository --repository-name sairam-strapi-ecr --region ap-south-1
        fi

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: docker build -t strapi-app:latest .

    - name: Set commit SHA
      run: echo "COMMIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

    - name: Tag Docker image
      run: |
        docker tag strapi-app:latest 242201300764.dkr.ecr.ap-south-1.amazonaws.com/sairam-strapi-ecr:latest
        docker tag strapi-app:latest 242201300764.dkr.ecr.ap-south-1.amazonaws.com/sairam-strapi-ecr:$COMMIT_SHA

    - name: Push Docker image to ECR
      run: |
        docker push 242201300764.dkr.ecr.ap-south-1.amazonaws.com/sairam-strapi-ecr:latest
        docker push 242201300764.dkr.ecr.ap-south-1.amazonaws.com/sairam-strapi-ecr:$COMMIT_SHA

    - name: Image pushed successfully
      run: echo "✅ Docker image pushed to ECR with tag 'latest'"
